### ISSUE TITLE
Code blocks and italic

### ISSUE THREAD

**Issue by tremby** [hallison/vim-markdown#7]
I'm sometimes getting everything on the screen made italic, and I think it's to do with underscores being present in code blocks. It seems unstable -- if I scroll up line by line everything remains italic until I hit some line (which doesn't even have an underscore or asterisk) and then the whole screen becomes normal. Scrolling down again everything's still normal until some other point.

I could provide the file I'm working on at the moment if that would be any help, though I don't know exact steps to reproduce the problem.

**Comment by di** [comment]
This is not an issue specific to the vim-markdown script -- it occurs because Vim does not use the entire buffer to determine the proper syntax, in order to improve performance.

Using the following commands (or putting them in your `.vimrc`) should resolve this issue. This forces Vim to us a minimum of 100 lines to sync, and always start from the beginning of the buffer:

```
:syn sync minlines=100
:syn sync fromstart
```

**Comment by tremby** [comment]
Thanks, I'll try this.
