### ISSUE TITLE
Single bracket pair gets link highliting

### ISSUE THREAD

**Issue by gadamiak** [hallison/vim-markdown#9]
A single bracket pair like in example below gets link highlighting.

```
An example of false link match: [this text] and everything after it
will be highlighted as link.
```

**Comment by hallison** [comment]
The usage of links in your example it's wrong. See the Markdown link syntax in the project site on section of syntax of links (http://daringfireball.net/projects/markdown/syntax#link). Try typing like the following example:

```
This is a link is a link to [Github][] and this to
[Vim-Markdown](http://githu.com/hallison/vim-markdown).

[github]: http://www.google.com/
  "Github Social Code"
```

This issue is not a bug in the Vim-Markdown syntax plugin.

Thanks for your contribution.

**Comment by gadamiak** [comment]
I know the Markdown syntax and what you provided is right. However this issue is about **a false match**. I guess it was not clear enough.

I my example the text in single bracket pair **is not meant to be a link** but just a [text in brackets](Git markdown parser gets it right). It gets a link highlight, however, which is not correct.

**Comment by hallison** [comment]
I'm sorry. Now, I understood. I'll solve this problem.

Thank you for your contribution.

**Comment by hallison** [comment]
Hello,

Actually, I am rewriting all sources of the plugin. No commits, yet. Please, wait for good news.

Thanks for all.
